version: '3'
services:
  app:
    image: wandonium/flask-book-api
    container_name: flask-book-api
    ports: 
      - 8000:5000
  proxy:
    image: wandonium/flask-proxy
    container_name: flask-proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - app