version: '3'
services:
  app:
    build: flask
    volumes:
      - app:/app
    ports:      - "8000:8000"
    links:
      - redis:redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
  proxy:
    build: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  app: