version: '3'
services:
  app:
    image: wandonium/flask-book-api
    container_name: flask-book-api
    environment:
      - VIRTUAL_HOST=flask-book-api.m.hillarywando.com,www.flask-book-api.m.hillarywando.com
    networks:
      - proxy_net
networks:
  proxy_net:
    driver: bridge